import test from 'node:test'
import assert from 'node:assert/strict'
import { exportJWK, generateKeyPair, SignJWT } from 'jose'
import worker from '../server/cloudflare-worker/worker.js'
import { clearJwksCacheForTests } from '../server/cloudflare-worker/auth.js'

const ISSUER='https://fixture.supabase.co/auth/v1', URL='https://fixture.supabase.co', AUD='authenticated'
const { privateKey, publicKey }=await generateKeyPair('RS256'); const jwk={...(await exportJWK(publicKey)),kid:'admin-test',alg:'RS256',use:'sig'}
async function token(sub, extra={}) { return new SignJWT({email:'ignored@example.test',app_metadata:{role:'admin'},...extra}).setProtectedHeader({alg:'RS256',kid:'admin-test'}).setIssuer(ISSUER).setAudience(AUD).setSubject(sub).setIssuedAt().setExpirationTime('5m').sign(privateKey) }
function db(roles={}) { const users=new Map(Object.keys(roles).map((sub)=>[sub,`internal-${sub}`])); const calls=[]; return { calls, prepare(sql){ const empty=async()=>({results:[]}); return { all:empty, bind(...args){ return { first:async()=> /FROM users WHERE auth_subject/.test(sql)?(users.get(args[0])?{id:users.get(args[0])}:null):null, all:async()=>{ if(/FROM user_roles/.test(sql)){const role=roles[args[0].replace('internal-','')];return {results:role?[{role}]:[]} } return {results:[]} }, run:async()=>{ if(/INSERT INTO users/.test(sql)) users.set(args[1],args[0]); calls.push({sql,args}); return {success:true} } } } } } } }
async function request(path, sub, env, init={}) { const headers=sub?{Authorization:`Bearer ${await token(sub,init.claims)}`}:{}; return worker.fetch(new Request(`https://worker.test${path}`,{method:init.method||'GET',headers:{...headers,...(init.headers||{})},body:init.body?JSON.stringify(init.body):undefined}),env) }
test('admin HTTP permissions use D1 role, never JWT metadata', async()=>{ const old=globalThis.fetch; clearJwksCacheForTests(); globalThis.fetch=async()=>new Response(JSON.stringify({keys:[jwk]})); try { const env={DB:db({admin:'admin',editor:'editor',support:'support',inactive:null}),SUPABASE_URL:URL,SUPABASE_JWT_ISSUER:ISSUER,SUPABASE_JWT_AUDIENCE:AUD}; assert.equal((await request('/admin/me',null,env)).status,401); assert.equal((await request('/admin/me','user',env,{claims:{app_metadata:{role:'admin'}}})).status,403); assert.equal((await request('/admin/announcements','admin',env)).status,200); assert.equal((await request('/admin/announcements','editor',env,{method:'POST',body:{title:'Duyuru',message:'Metin'}})).status,201); assert.equal((await request('/admin/settings/maintenance_mode','editor',env,{method:'PUT',body:{value:'true'}})).status,403); assert.equal((await request('/admin/announcements','support',env)).status,200); assert.equal((await request('/admin/announcements','support',env,{method:'POST',body:{title:'x',message:'y'}})).status,403); assert.equal((await request('/admin/audit','editor',env)).status,403) } finally {globalThis.fetch=old;clearJwksCacheForTests()} })
test('audit HTTP rejects malformed cursor and caps limit', async()=>{ const old=globalThis.fetch;clearJwksCacheForTests();globalThis.fetch=async()=>new Response(JSON.stringify({keys:[jwk]}));try{const database=db({admin:'admin'});const env={DB:database,SUPABASE_URL:URL,SUPABASE_JWT_ISSUER:ISSUER,SUPABASE_JWT_AUDIENCE:AUD};assert.equal((await request('/admin/audit?cursor=!', 'admin',env)).status,400);assert.equal((await request('/admin/audit?limit=999','admin',env)).status,200);assert.ok(database.calls.length>=0)}finally{globalThis.fetch=old;clearJwksCacheForTests()}})
