import test from 'node:test'
import assert from 'node:assert/strict'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { readFile } from 'node:fs/promises'
import { buildIssuesValuesDryRun, toMinorTry } from '../scripts/catalog/import-issues-values.js'
import { validateIssuesValues } from '../scripts/catalog/lib/validate-issues-values.js'
const exec=promisify(execFile)
test('issues baseline and review policy preserve source counts',async()=>{const r=await buildIssuesValuesDryRun();assert.deepEqual([r.counts.problemArchetypes,r.counts.problemApplicability,r.problemSummary.normalizedTitles,r.counts.maintenanceItems,r.counts.referenceValues,r.counts.valuationFactors],[20,740,137,14,31,8]);assert.equal(r.canImport,true);assert.equal(r.reviewSummary.warningEvents,935);assert.equal(r.problemSummary.archetypeMatched,1);assert.equal(r.problemSummary.legacyScoped,651)})
test('minor TRY conversion and reference policy are safe',async()=>{const r=await buildIssuesValuesDryRun();assert.equal(toMinorTry(1550000),155000000);assert.equal(toMinorTry(-1),null);const a3=r.records.referenceValues.find(x=>x.amount_minor===155000000);assert.ok(a3);assert.equal(a3.currency,'TRY');assert.equal(a3.value_type,'imported_legacy');assert.equal(a3.effective_at,0)})
test('validator blocks empty scope and collisions but warnings can import',()=>{const p={revisionId:'r',problemArchetypes:[],variants:[],generations:[],maintenanceItems:[],referenceValues:[],valuationFactors:[],reviewCandidates:[{type:'review',sourceKey:'x',reason:'x'}],sourceManifestStable:true,problemApplicability:[{id:'x',revision_id:'r'}]};assert.equal(validateIssuesValues(p).canImport,false);p.problemApplicability=[];assert.equal(validateIssuesValues(p).canImport,true)})
test('CLI JSON is offline and remote is rejected',async()=>{const source=await readFile(new URL('../scripts/catalog/import-issues-values.js',import.meta.url),'utf8');assert.doesNotMatch(source,/fetch\s*\(|wrangler|writeFile|D1\.(prepare|batch|exec)/i);const {stdout}=await exec(process.execPath,['scripts/catalog/import-issues-values.js','--json']);const json=JSON.parse(stdout);for(const key of ['mode','remoteAccess','canImport','counts','problemSummary','maintenanceSummary','referenceValueSummary','reviewSummary','integrity','reviewCandidates','plan'])assert.ok(key in json);await assert.rejects(exec(process.execPath,['scripts/catalog/import-issues-values.js','--remote']))})
