import { ALL_TABLES } from './schemas.js'
import { revision } from './repository.js'
const audit = (db,a,action,type,id,payload='{}') => db.prepare('INSERT INTO admin_audit_logs(id,actor_user_id,action,target_type,target_id,payload,created_at) VALUES(?1,?2,?3,?4,?5,?6,?7)').bind(crypto.randomUUID(),a.userId,action,type,id,payload,Date.now())
export async function createRevision(env,actor,body={}) {
  const source=body.cloneFromPublished?await env.DB.prepare("SELECT published_revision_id id FROM catalog_state WHERE singleton_key='active'").first():null,id=`catalog:edit:${crypto.randomUUID()}`,now=Date.now(),next=Number((await env.DB.prepare('SELECT COALESCE(MAX(revision_number),0)+1 n FROM catalog_revisions').first())?.n||1)
  const statements=[env.DB.prepare("INSERT INTO catalog_revisions(id,revision_number,status,label,notes,source_type,created_by,created_at) VALUES(?1,?2,'draft',?3,?4,'admin-edit',?5,?6)").bind(id,next,String(body.label||'Yeni katalog taslağı').slice(0,120),String(body.notes||'').slice(0,1000),actor.userId,now)]
  if(source?.id)for(const schema of Object.values(ALL_TABLES)){const columns=(await env.DB.prepare(`PRAGMA table_info(${schema.table})`).all()).results.map(x=>x.name).filter(x=>x!=='revision_id'),globalId=['catalog_generation_engines','catalog_generation_transmissions'].includes(schema.table),select=columns.map(c=>globalId&&c==='id'?"id||':'||?3":c).join(','),prepared=env.DB.prepare(`INSERT INTO ${schema.table}(revision_id,${columns.join(',')}) SELECT ?1,${select} FROM ${schema.table} WHERE revision_id=?2`);statements.push(globalId?prepared.bind(id,source.id,id.slice(-12)):prepared.bind(id,source.id))}
  statements.push(audit(env.DB,actor,'catalog.revision.create','catalog_revision',id,JSON.stringify({cloned:Boolean(source?.id)})));await env.DB.batch(statements);return{id,status:'draft',clonedFrom:source?.id||null}
}
export async function publishRevision(env,actor,id){const rev=await revision(env.DB,id);if(!rev)return{status:404,error:'Revision bulunamadı'};const state=await env.DB.prepare("SELECT published_revision_id FROM catalog_state WHERE singleton_key='active'").first();if(state?.published_revision_id===id&&rev.status==='published')return{status:200,value:{id,alreadyPublished:true}};if(rev.status!=='draft'||!rev.validated_at||rev.validation_error_count!==0)return{status:422,error:'Revision doğrulanmış ve hatasız draft olmalıdır'};const c=await env.DB.prepare('SELECT (SELECT COUNT(*) FROM catalog_brands WHERE revision_id=?1) brands,(SELECT COUNT(*) FROM catalog_models WHERE revision_id=?1) models,(SELECT COUNT(*) FROM catalog_generations WHERE revision_id=?1) generations').bind(id).first();if(!c?.brands||!c?.models||!c?.generations)return{status:422,error:'Kritik katalog tabloları boş olamaz'};const now=Date.now(),s=[];if(state?.published_revision_id&&state.published_revision_id!==id)s.push(env.DB.prepare("UPDATE catalog_revisions SET status='archived',archived_at=?1 WHERE id=?2 AND status='published'").bind(now,state.published_revision_id));s.push(env.DB.prepare("UPDATE catalog_revisions SET status='published',published_at=?1,archived_at=NULL WHERE id=?2 AND status='draft'").bind(now,id),env.DB.prepare("INSERT INTO catalog_state(singleton_key,published_revision_id,previous_revision_id,updated_at,updated_by)VALUES('active',?1,?2,?3,?4) ON CONFLICT(singleton_key) DO UPDATE SET previous_revision_id=catalog_state.published_revision_id,published_revision_id=excluded.published_revision_id,updated_at=excluded.updated_at,updated_by=excluded.updated_by").bind(id,state?.published_revision_id||null,now,actor.userId),env.DB.prepare("INSERT INTO catalog_publication_history(id,from_revision_id,to_revision_id,action,actor_user_id,created_at)VALUES(?1,?2,?3,'publish',?4,?5)").bind(crypto.randomUUID(),state?.published_revision_id||null,id,actor.userId,now),audit(env.DB,actor,'catalog.publish','catalog_revision',id));await env.DB.batch(s);return{status:200,value:{id,published:true}}}
export async function rollbackRevision(env,actor,body){const id=body?.targetRevisionId,reason=String(body?.reason||'').trim();if(!id||reason.length<3||reason.length>500)return{status:400,error:'Hedef revision ve gerekçe zorunludur'};const target=await revision(env.DB,id),state=await env.DB.prepare("SELECT published_revision_id FROM catalog_state WHERE singleton_key='active'").first();if(state?.published_revision_id===id)return{status:200,value:{id,alreadyActive:true}};const was=await env.DB.prepare("SELECT 1 ok FROM catalog_publication_history WHERE to_revision_id=?1 AND action='publish' LIMIT 1").bind(id).first();if(!target||!was||!['archived','published'].includes(target.status))return{status:422,error:'Hedef daha önce yayınlanmış güvenli snapshot olmalıdır'};const now=Date.now();await env.DB.batch([env.DB.prepare("UPDATE catalog_revisions SET status='archived',archived_at=?1 WHERE id=?2 AND status='published'").bind(now,state?.published_revision_id),env.DB.prepare("UPDATE catalog_revisions SET status='published',published_at=?1,archived_at=NULL WHERE id=?2").bind(now,id),env.DB.prepare("UPDATE catalog_state SET previous_revision_id=published_revision_id,published_revision_id=?1,updated_at=?2,updated_by=?3 WHERE singleton_key='active'").bind(id,now,actor.userId),env.DB.prepare("INSERT INTO catalog_publication_history(id,from_revision_id,to_revision_id,action,actor_user_id,created_at,reason)VALUES(?1,?2,?3,'rollback',?4,?5,?6)").bind(crypto.randomUUID(),state?.published_revision_id||null,id,actor.userId,now,reason),audit(env.DB,actor,'catalog.rollback','catalog_revision',id,JSON.stringify({reason}))]);return{status:200,value:{id,rolledBack:true}}}
