import { counts, nextCursor, page, publishedRevision } from './repository.js'
const reply=(body,status,cors,etag)=>new Response(status===304?null:JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8',...cors,'Cache-Control':status===304?'public, max-age=60':'public, max-age=60, stale-while-revalidate=300',...(etag?{ETag:etag}:{})}})
const safeRows=(rows=[])=>rows.map(item=>{const row={...item};for(const key of['source_file','source_key','created_at','updated_at','created_by','updated_by','notes'])delete row[key];return row})
async function list(db,sql,args,limit){return safeRows((await db.prepare(`${sql} LIMIT ?${args.length+1}`).bind(...args,limit).all()).results)}
async function context(request,env,cors){const rev=await publishedRevision(env.DB);if(!rev)return{response:reply({available:false,source:'legacy-fallback-required'},200,cors)};const etag=`"catalog-${rev.id}-${rev.published_at||0}"`;return request.headers.get('If-None-Match')===etag?{response:reply(null,304,cors,etag)}:{rev,etag}}
export async function handlePublicCatalog(request,env,url,cors){if(!['GET','HEAD'].includes(request.method))return reply({error:'Sadece GET/HEAD destekleniyor'},405,cors);if(!env.DB)return reply({available:false,source:'legacy-fallback-required'},200,cors);const ctx=await context(request,env,cors);if(ctx.response)return ctx.response;const rev=ctx.rev.id,path=url.pathname,{limit,cursor}=page(url);let body
  if(path==='/catalog/meta'){body={available:true,revision:rev,publishedAt:ctx.rev.published_at,...await counts(env.DB,rev)}}
  else if(path==='/catalog/brands'){const items=await list(env.DB,'SELECT id,slug,display_name,normalized_name,country_code,sort_order FROM catalog_brands WHERE revision_id=?1 AND active=1 AND id>?2 ORDER BY id',[rev,cursor],limit);body={items,nextCursor:items.length===limit?nextCursor(items):null}}
  else if(path==='/catalog/models'||path==='/catalog/generations'){const models=path.endsWith('models'),parent=url.searchParams.get(models?'brand_id':'model_id');if(!parent)return reply({error:`${models?'brand_id':'model_id'} zorunludur`},400,cors);const table=models?'catalog_models':'catalog_generations',parentColumn=models?'brand_id':'model_id',columns=models?'id,brand_id,slug,display_name,normalized_name,sort_order':'id,model_id,code,display_name,normalized_name,year_start,year_end,body_types_json';const items=await list(env.DB,`SELECT ${columns} FROM ${table} WHERE revision_id=?1 AND active=1 AND ${parentColumn}=?2 AND id>?3 ORDER BY id`,[rev,parent,cursor],limit);body={items,nextCursor:items.length===limit?nextCursor(items):null}}
  else if(['/catalog/engines','/catalog/transmissions','/catalog/packages'].includes(path)){const generation=url.searchParams.get('generation_id');if(!generation)return reply({error:'generation_id zorunludur'},400,cors);const key=path.split('/').at(-1),cfg={engines:['catalog_engines','catalog_generation_engines','engine_id','e.display_name,e.code,e.fuel_type,e.power_hp'],transmissions:['catalog_transmissions','catalog_generation_transmissions','transmission_id','e.display_name,e.code,e.transmission_type,e.gear_count'],packages:['catalog_packages','catalog_generation_packages','package_id','e.display_name,e.code,e.description']}[key],items=await list(env.DB,`SELECT e.id,${cfg[3]} FROM ${cfg[0]} e JOIN ${cfg[1]} r ON r.revision_id=e.revision_id AND r.${cfg[2]}=e.id WHERE e.revision_id=?1 AND e.active=1 AND r.generation_id=?2 AND e.id>?3 ORDER BY e.id`,[rev,generation,cursor],limit);body={items,nextCursor:items.length===limit?nextCursor(items):null}}
  else if(path==='/catalog/variants'){const generation=url.searchParams.get('generation_id');if(!generation)return reply({error:'generation_id zorunludur'},400,cors);const items=await list(env.DB,'SELECT id,generation_id,engine_id,transmission_id,package_id,display_name,model_year,year_start,year_end,body_type,drivetrain FROM catalog_vehicle_variants WHERE revision_id=?1 AND active=1 AND generation_id=?2 AND id>?3 ORDER BY id',[rev,generation,cursor],limit);body={items,nextCursor:items.length===limit?nextCursor(items):null}}
  else if(/^\/catalog\/generations\/[^/]+$/.test(path)){const id=decodeURIComponent(path.split('/').at(-1)),generation=await env.DB.prepare('SELECT g.id,g.code,g.display_name,g.year_start,g.year_end,g.body_types_json,m.id model_id,m.display_name model_name,b.id brand_id,b.display_name brand_name FROM catalog_generations g JOIN catalog_models m ON m.revision_id=g.revision_id AND m.id=g.model_id AND m.active=1 JOIN catalog_brands b ON b.revision_id=m.revision_id AND b.id=m.brand_id AND b.active=1 WHERE g.revision_id=?1 AND g.id=?2 AND g.active=1').bind(rev,id).first();if(!generation)return reply({error:'Nesil bulunamadı'},404,cors);const variantCount=Number((await env.DB.prepare('SELECT COUNT(*) n FROM catalog_vehicle_variants WHERE revision_id=?1 AND generation_id=?2 AND active=1').bind(rev,id).first())?.n||0);body={...generation,variantCount}}
  else if(/^\/catalog\/variants\/[^/]+$/.test(path)){const id=decodeURIComponent(path.split('/').at(-1)),variant=await env.DB.prepare('SELECT v.id,v.display_name,v.model_year,v.year_start,v.year_end,v.body_type,v.drivetrain,v.source_confidence,g.id generation_id,g.display_name generation_name,m.id model_id,m.display_name model_name,b.id brand_id,b.display_name brand_name,e.id engine_id,e.display_name engine_name,t.id transmission_id,t.display_name transmission_name,p.id package_id,p.display_name package_name FROM catalog_vehicle_variants v JOIN catalog_generations g ON g.revision_id=v.revision_id AND g.id=v.generation_id JOIN catalog_models m ON m.revision_id=g.revision_id AND m.id=g.model_id JOIN catalog_brands b ON b.revision_id=m.revision_id AND b.id=m.brand_id LEFT JOIN catalog_engines e ON e.revision_id=v.revision_id AND e.id=v.engine_id LEFT JOIN catalog_transmissions t ON t.revision_id=v.revision_id AND t.id=v.transmission_id LEFT JOIN catalog_packages p ON p.revision_id=v.revision_id AND p.id=v.package_id WHERE v.revision_id=?1 AND v.id=?2 AND v.active=1 AND g.active=1 AND m.active=1 AND b.active=1').bind(rev,id).first();if(!variant)return reply({error:'Varyant bulunamadı'},404,cors);const equipment=variant.package_id?await list(env.DB,'SELECT e.id,e.display_name,e.category,r.availability FROM catalog_equipment e JOIN catalog_package_equipment r ON r.revision_id=e.revision_id AND r.equipment_id=e.id WHERE e.revision_id=?1 AND r.package_id=?2 AND e.active=1 ORDER BY e.id',[rev,variant.package_id],100):[],references=safeRows((await env.DB.prepare('SELECT id,amount_minor,currency,value_type,effective_at,confidence FROM catalog_reference_values WHERE revision_id=?1 AND active=1 AND (vehicle_variant_id=?2 OR (vehicle_variant_id IS NULL AND generation_id=?3)) ORDER BY effective_at DESC LIMIT 20').bind(rev,id,variant.generation_id).all()).results);body={...variant,equipment,referenceValues:references,referenceValueNotice:'Referans değerler gözlemseldir; kesin satış veya ekspertiz fiyatı değildir.'}}
  else if(path==='/catalog/problems'){const generation=url.searchParams.get('generation_id'),variant=url.searchParams.get('variant_id');if(!generation&&!variant)return reply({error:'generation_id veya variant_id zorunludur'},400,cors);const rows=await env.DB.prepare('SELECT id,title_override title,description_override description,severity_override severity,confidence,evidence_status,symptoms_json,checks_json,repair_guidance FROM catalog_problem_applicability WHERE revision_id=?1 AND active=1 AND ((?2 IS NOT NULL AND generation_id=?2) OR (?3 IS NOT NULL AND vehicle_variant_id=?3)) ORDER BY id LIMIT ?4').bind(rev,generation,variant,limit).all();body={items:safeRows(rows.results),notice:'Bunlar kesin arıza iddiası değil, kontrol edilmesi gereken olası durumlardır.'}}
  else if(path==='/catalog/maintenance'){const generation=url.searchParams.get('generation_id'),variant=url.searchParams.get('variant_id');if(!generation&&!variant)return reply({error:'generation_id veya variant_id zorunludur'},400,cors);const rows=await env.DB.prepare("SELECT a.id,i.title,i.category,i.description,i.default_interval_km,i.default_interval_months,a.interval_km_override,a.interval_months_override,a.confidence FROM catalog_maintenance_applicability a JOIN catalog_maintenance_items i ON i.revision_id=a.revision_id AND i.id=a.maintenance_item_id AND i.active=1 WHERE a.revision_id=?1 AND ((?2 IS NOT NULL AND a.generation_id=?2) OR (?3 IS NOT NULL AND a.vehicle_variant_id=?3) OR a.scope_type='global') ORDER BY a.id LIMIT ?4").bind(rev,generation,variant,limit).all();body={items:safeRows(rows.results)}}
  else if(path==='/catalog/search'){const q=(url.searchParams.get('q')||'').trim().toLocaleLowerCase('tr-TR');if(q.length<2||q.length>80)return reply({error:'Arama 2-80 karakter olmalıdır'},400,cors);const term=`%${q.replace(/[\\%_]/g,'\\$&')}%`,rows=await env.DB.prepare("SELECT type,id,display_name FROM (SELECT 'brand' type,id,display_name,normalized_name FROM catalog_brands WHERE revision_id=?1 AND active=1 UNION ALL SELECT 'model',id,display_name,normalized_name FROM catalog_models WHERE revision_id=?1 AND active=1 UNION ALL SELECT 'generation',id,display_name,normalized_name FROM catalog_generations WHERE revision_id=?1 AND active=1 UNION ALL SELECT 'engine',id,display_name,normalized_name FROM catalog_engines WHERE revision_id=?1 AND active=1 UNION ALL SELECT 'package',id,display_name,normalized_name FROM catalog_packages WHERE revision_id=?1 AND active=1) WHERE normalized_name LIKE ?2 ESCAPE '\\' ORDER BY type,id LIMIT ?3").bind(rev,term,limit).all();body={items:safeRows(rows.results)}}
  else return null
  return request.method==='HEAD'?reply(null,200,cors,ctx.etag):reply(body,200,cors,ctx.etag)
}
