export const ENTITY_REGISTRY = Object.freeze({
  brands:{table:'catalog_brands',fields:['slug','display_name','normalized_name','country_code','sort_order','active','source_key','source_confidence']},
  models:{table:'catalog_models',fields:['brand_id','slug','display_name','normalized_name','sort_order','active','source_key','source_confidence']},
  generations:{table:'catalog_generations',fields:['model_id','code','display_name','normalized_name','year_start','year_end','body_types_json','sort_order','active','source_key','source_confidence']},
  engines:{table:'catalog_engines',fields:['code','display_name','normalized_name','fuel_type','displacement_cc','power_hp','power_kw','torque_nm','aspiration','cylinder_count','year_start','year_end','sort_order','active','source_key','source_confidence']},
  transmissions:{table:'catalog_transmissions',fields:['code','display_name','normalized_name','transmission_type','gear_count','manufacturer','clutch_type','year_start','year_end','sort_order','active','source_key','source_confidence']},
  packages:{table:'catalog_packages',fields:['display_name','normalized_name','code','description','active','sort_order','source_key','source_confidence']},
  equipment:{table:'catalog_equipment',fields:['category','display_name','normalized_name','description','active','sort_order','source_key','source_confidence']},
  vehicleVariants:{table:'catalog_vehicle_variants',fields:['generation_id','engine_id','transmission_id','package_id','model_year','year_start','year_end','body_type','drivetrain','fuel_type_override','power_hp_override','display_name','normalized_name','active','source_key','source_confidence','legacy_vehicle_key']},
  problemArchetypes:{table:'catalog_problem_archetypes',fields:['code','title','normalized_title','category','default_severity','summary','diagnostic_guidance','active','source_key','source_confidence']},
  problemApplicability:{table:'catalog_problem_applicability',fields:['problem_archetype_id','generation_id','engine_id','transmission_id','package_id','vehicle_variant_id','fuel_type_filter','transmission_type_filter','title_override','description_override','severity_override','symptoms_json','checks_json','repair_guidance','confidence','evidence_status','source_key','legacy_vehicle_key','active']},
  maintenanceItems:{table:'catalog_maintenance_items',fields:['code','title','normalized_title','category','description','default_interval_km','default_interval_months','priority','active','source_key','source_confidence']},
  maintenanceApplicability:{table:'catalog_maintenance_applicability',fields:['maintenance_item_id','scope_type','generation_id','engine_id','transmission_id','package_id','vehicle_variant_id','fuel_type_filter','interval_km_override','interval_months_override','year_start','year_end','notes','confidence','source_key']},
  referenceValues:{table:'catalog_reference_values',fields:['vehicle_variant_id','generation_id','engine_id','transmission_id','package_id','model_year','amount_minor','currency','value_type','effective_at','valid_until','mileage_min','mileage_max','source_name','source_url','source_observed_at','confidence','source_key','active']},
  valuationFactors:{table:'catalog_valuation_factors',fields:['factor_type','factor_key','display_name','numeric_value','value_json','unit','description','active','source_key','source_confidence']}
})
export const RELATIONS=Object.freeze({generationEngines:{table:'catalog_generation_engines',fields:['generation_id','engine_id','year_start','year_end','source_confidence']},generationTransmissions:{table:'catalog_generation_transmissions',fields:['generation_id','transmission_id','year_start','year_end','source_confidence']},generationPackages:{table:'catalog_generation_packages',fields:['generation_id','package_id','year_start','year_end','body_type','source_key','source_confidence']},packageEquipment:{table:'catalog_package_equipment',fields:['package_id','equipment_id','availability','standard','notes','source_confidence']}})
export const ALL_TABLES=Object.freeze({...ENTITY_REGISTRY,...RELATIONS})
export function entitySchema(name){return ALL_TABLES[name]||null}
export function cleanPayload(schema,body){const out={};for(const field of schema.fields)if(Object.hasOwn(body||{},field))out[field]=body[field];return out}
