// Formlar ve filtre kutuları aynı sabit değer kümesini paylaşır — DB CHECK
// kısıtlarıyla birebir eşleşir (0008_catalog_issues_maintenance_values.sql).
export const FIELD_OPTIONS={confidence:['unknown','low','medium','high'],severity:['unknown','low','medium','high','critical'],evidence:['unverified','reviewed','verified','rejected'],scope:['global','filtered','vehicle'],valueType:['reference','asking_median','transaction_estimate','manual','imported_legacy']}
export const ENTITY_FORMS={
brands:{label:'Marka',fields:[['display_name','Görünen ad','text',true],['slug','Slug','text',true],['normalized_name','Normalize ad','text',true],['country_code','Ülke kodu','text'],['sort_order','Sıra','number'],['active','Aktif','boolean'],['source_confidence','Confidence','confidence']]},
models:{label:'Model',fields:[['brand_id','Marka','parent:brands',true],['display_name','Görünen ad','text',true],['slug','Slug','text',true],['normalized_name','Normalize ad','text',true],['sort_order','Sıra','number'],['active','Aktif','boolean'],['source_confidence','Confidence','confidence']]},
generations:{label:'Nesil',fields:[['model_id','Model','parent:models',true],['code','Kod','text'],['display_name','Görünen ad','text',true],['normalized_name','Normalize ad','text',true],['year_start','Başlangıç yılı','number',true],['year_end','Bitiş yılı','number'],['body_types_json','Gövde tipleri','text'],['sort_order','Sıra','number'],['active','Aktif','boolean'],['source_confidence','Confidence','confidence']]},
engines:{label:'Motor',fields:[['display_name','Görünen ad','text',true],['normalized_name','Normalize ad','text',true],['code','Kod','text'],['fuel_type','Yakıt','text'],['displacement_cc','Hacim cc','number'],['power_hp','Güç hp','number'],['power_kw','Güç kW','number'],['torque_nm','Tork Nm','number'],['aspiration','Besleme','text'],['cylinder_count','Silindir','number'],['year_start','Başlangıç yılı','number'],['year_end','Bitiş yılı','number'],['active','Aktif','boolean'],['source_confidence','Confidence','confidence']]},
transmissions:{label:'Şanzıman',fields:[['display_name','Görünen ad','text',true],['normalized_name','Normalize ad','text',true],['code','Kod','text'],['transmission_type','Tip','text'],['gear_count','Vites','number'],['manufacturer','Üretici','text'],['clutch_type','Kavrama','text'],['year_start','Başlangıç yılı','number'],['year_end','Bitiş yılı','number'],['active','Aktif','boolean'],['source_confidence','Confidence','confidence']]},
packages:{label:'Paket',fields:[['display_name','Ad','text',true],['normalized_name','Normalize ad','text',true],['code','Kod','text'],['description','Açıklama','textarea'],['sort_order','Sıra','number'],['active','Aktif','boolean'],['source_confidence','Confidence','confidence']]},
equipment:{label:'Donanım',fields:[['category','Kategori','text'],['display_name','Ad','text',true],['normalized_name','Normalize ad','text',true],['description','Açıklama','textarea'],['sort_order','Sıra','number'],['active','Aktif','boolean'],['source_confidence','Confidence','confidence']]},
vehicleVariants:{label:'Varyant',fields:[['generation_id','Nesil','parent:generations',true],['engine_id','Motor','parent:engines'],['transmission_id','Şanzıman','parent:transmissions'],['package_id','Paket','parent:packages'],['display_name','Canonical ad','text',true],['normalized_name','Normalize ad','text',true],['model_year','Model yılı','number'],['year_start','Başlangıç yılı','number'],['year_end','Bitiş yılı','number'],['body_type','Gövde','text'],['drivetrain','Çekiş','text'],['fuel_type_override','Yakıt override','text'],['power_hp_override','Güç override','number'],['legacy_vehicle_key','Legacy key','readonly'],['active','Aktif','boolean'],['source_confidence','Confidence','confidence']]},
problemArchetypes:{label:'Sorun arketipi',fields:[['title','Başlık','text',true],['normalized_title','Normalize başlık','text',true],['code','Kod','text'],['category','Kategori','text'],['default_severity','Şiddet','severity'],['summary','Özet','textarea'],['diagnostic_guidance','Teşhis rehberi','textarea'],['active','Aktif','boolean'],['source_confidence','Confidence','confidence']]},
problemApplicability:{label:'Sorun kapsamı',fields:[['problem_archetype_id','Arketip','parent:problemArchetypes'],['generation_id','Nesil','parent:generations'],['engine_id','Motor','parent:engines'],['transmission_id','Şanzıman','parent:transmissions'],['package_id','Paket','parent:packages'],['vehicle_variant_id','Varyant','parent:vehicleVariants'],['fuel_type_filter','Yakıt filtresi','text'],['transmission_type_filter','Şanzıman filtresi','text'],['title_override','Başlık','text'],['description_override','Açıklama','textarea'],['severity_override','Şiddet','severity'],['confidence','Confidence','confidence'],['evidence_status','Kanıt durumu','evidence'],['legacy_vehicle_key','Legacy key','readonly'],['active','Aktif','boolean']]},
maintenanceItems:{label:'Bakım kalemi',fields:[['title','Başlık','text',true],['normalized_title','Normalize başlık','text',true],['code','Kod','text'],['category','Kategori','text'],['description','Açıklama','textarea'],['default_interval_km','Varsayılan km','number'],['default_interval_months','Varsayılan ay','number'],['priority','Öncelik','text'],['active','Aktif','boolean'],['source_confidence','Confidence','confidence']]},
maintenanceApplicability:{label:'Bakım kapsamı',fields:[['maintenance_item_id','Bakım kalemi','parent:maintenanceItems',true],['scope_type','Kapsam tipi','scope',true],['generation_id','Nesil','parent:generations'],['engine_id','Motor','parent:engines'],['transmission_id','Şanzıman','parent:transmissions'],['package_id','Paket','parent:packages'],['vehicle_variant_id','Varyant','parent:vehicleVariants'],['fuel_type_filter','Yakıt filtresi','text'],['interval_km_override','Km override','number'],['interval_months_override','Ay override','number'],['year_start','Başlangıç yılı','number'],['year_end','Bitiş yılı','number'],['notes','Not','textarea'],['confidence','Confidence','confidence']]},
referenceValues:{label:'Referans değer',fields:[['generation_id','Nesil','parent:generations'],['vehicle_variant_id','Varyant','parent:vehicleVariants'],['amount_try','Tutar (TL)','money',true],['value_type','Değer tipi','valueType',true],['effective_at','Geçerlilik başlangıcı','date',true],['valid_until','Geçerlilik sonu','date'],['mileage_min','Minimum km','number'],['mileage_max','Maksimum km','number'],['source_name','Kaynak adı','text'],['source_url','Kaynak URL','text'],['confidence','Confidence','confidence'],['active','Aktif','boolean']]},
valuationFactors:{label:'Değerleme faktörü',fields:[['factor_type','Faktör tipi','text',true],['factor_key','Anahtar','text',true],['display_name','Görünen ad','text',true],['numeric_value','Sayısal değer','number'],['value_json','Structured JSON','textarea'],['unit','Birim','text'],['description','Açıklama','textarea'],['active','Aktif','boolean'],['source_confidence','Confidence','confidence']]}}
export function validateEntityForm(entity,data){const form=ENTITY_FORMS[entity],errors={};if(!form)return{entity:'Geçersiz entity'};for(const[name,,type,required]of form.fields){const value=data[name];if(required&&(value==null||String(value).trim()===''))errors[name]='Zorunlu alan';if(type==='number'&&value!==''&&value!=null&&(!Number.isFinite(Number(value))||Number(value)<0))errors[name]='Geçersiz pozitif sayı'}if(data.year_start&&data.year_end&&Number(data.year_end)<Number(data.year_start))errors.year_end='Bitiş başlangıçtan önce olamaz';if(entity==='problemApplicability'&&!['problem_archetype_id','generation_id','engine_id','transmission_id','package_id','vehicle_variant_id','fuel_type_filter','transmission_type_filter'].some(key=>data[key]))errors.scope='En az bir kapsam zorunludur';if(entity==='referenceValues'&&!data.generation_id&&!data.vehicle_variant_id)errors.scope='Nesil veya varyant zorunludur';if(entity==='valuationFactors'&&!data.numeric_value&&!data.value_json)errors.value='Sayısal veya structured değer zorunludur';return errors}
