import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import PageContainer from '../components/Layout/PageContainer'
import { useAuth } from '../contexts/AuthContext'
import { getAccessToken } from '../services/authService'
import { PROXY_BASE_URL } from '../services/aiService'

async function api(path, method = 'GET', body) { const token = await getAccessToken(); const res = await fetch(`${PROXY_BASE_URL.replace(/\/$/, '')}${path}`, { method, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); const data = await res.json().catch(() => null); if (!res.ok) throw new Error(res.status === 403 ? 'Bu alana erişim yetkiniz yok.' : 'İşlem tamamlanamadı.'); return data }
export default function AdminPage() { const { user }=useAuth(); const [state,setState]=useState('loading'); const [items,setItems]=useState([]); const [title,setTitle]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const load=()=>api('/admin/announcements').then((d)=>{setItems(d.items);setState('ready')}).catch((e)=>{setError(e.message);setState('denied')}); useEffect(()=>{ if(user) load() },[user]); if(!user) return <PageContainer><p>Giriş yapmanız gerekiyor.</p></PageContainer>; if(state==='loading') return <PageContainer><p>Yetki kontrol ediliyor…</p></PageContainer>; if(state==='denied') return <PageContainer><p className="auth-error">{error}</p><Link to="/">Uygulamaya dön</Link></PageContainer>; async function create(e){e.preventDefault();try{await api('/admin/announcements','POST',{title,message});setTitle('');setMessage('');load()}catch(err){setError(err.message)}} return <PageContainer><section className="auth-card"><p className="eyebrow">YÖNETİM</p><h1>Duyurular</h1><p><Link to="/admin">Genel Bakış</Link> · <Link to="/admin/ayarlar">Ayarlar</Link> · <Link to="/admin/denetim-kaydi">Denetim Kaydı</Link> · <Link to="/">Uygulamaya dön</Link></p><form className="auth-form" onSubmit={create}><input value={title} maxLength="120" onChange={e=>setTitle(e.target.value)} placeholder="Başlık" required/><textarea value={message} maxLength="2000" onChange={e=>setMessage(e.target.value)} placeholder="Duyuru metni" required/><button className="btn btn-primary">Taslak oluştur</button></form>{error&&<p className="auth-error">{error}</p>}<div className="saved-list">{items.map(i=><div className="saved-item" key={i.id}><span className="saved-item-body"><b>{i.title}</b><span>{i.status}</span></span><button className="btn btn-secondary" onClick={()=>api(`/admin/announcements/${i.id}/publish`,'POST').then(load)}>Yayınla</button><button className="btn btn-secondary" onClick={()=>api(`/admin/announcements/${i.id}/archive`,'POST').then(load)}>Arşivle</button></div>)}</div></section></PageContainer> }
